# Site settings
title: "Prashant Baid"
email: prashantvbaid@gmail.com
description: "Duct Tape Dragon"
baseurl: ""
url: "http://prashantb.com/"
title_description: "The Sound of Silence"
title_image: "https://raw.githubusercontent.com/prashantbaid/prashantbaid.github.io/master/images/dp.jpg"
google_analytics: "UA-29156353-1"
disqus_account: prashantbaid
github_repository: https://github.com/prashantbaid/prashantbaid.github.io
post_limit: 7

# Social usernames/URLs
twitter_username: prashantbaid
github_username:  prashantbaid
instagram_username: prashantbaid
reddit_username:
stackoverflow_link: https://stackoverflow.com/users/648737/prashant-baid

# Footer
footer_left: "<i>\"Sin ought to be something exquisite, my dear boy.\"</i>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/prashantbaid/prashantbaid.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: :title/
exclude: [vendor]
