baseurl                  = "http://prashantb.com/"               # Your domain name. Must end with "/"
languageCode             = "en-us"
title                    = "PB"
theme                    = "sam"
pygmentsStyle            = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics          = "UA-29156353-1"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "/sam.ico"
    homepage             = "home"                        # What to call the home page link
    galleryFolder        = "images/"                     # Where you've put your images, after "/content/gallery/" (eg. "images/")
    clickablePhotos      = true                          # Allow links to the full size images
    smallPreviewImages   = true                          # Show thumbnails (small images) instead of using full size images on the gallery page
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # Folder for image thumbnails (small versions) after "/content/gallery/[galleryFolder]" (eg. "small/")
                                                         # For each image the small version has to have the same filename as the big version.
    footerText           = "Sin ought to be something exquisite, my dear boy"

# Metadata
    description          = "Prashant Baid's Blog"            # Max 160 characters show in search results
    twitterCard          = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage         = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts"
    text = "Blog"

